package com.mybatisDemo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ContentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public ContentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWareIsNull() {
            addCriterion("ware is null");
            return (Criteria) this;
        }

        public Criteria andWareIsNotNull() {
            addCriterion("ware is not null");
            return (Criteria) this;
        }

        public Criteria andWareEqualTo(String value) {
            addCriterion("ware =", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareNotEqualTo(String value) {
            addCriterion("ware <>", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareGreaterThan(String value) {
            addCriterion("ware >", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareGreaterThanOrEqualTo(String value) {
            addCriterion("ware >=", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareLessThan(String value) {
            addCriterion("ware <", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareLessThanOrEqualTo(String value) {
            addCriterion("ware <=", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareLike(String value) {
            addCriterion("ware like", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareNotLike(String value) {
            addCriterion("ware not like", value, "ware");
            return (Criteria) this;
        }

        public Criteria andWareIn(List<String> values) {
            addCriterion("ware in", values, "ware");
            return (Criteria) this;
        }

        public Criteria andWareNotIn(List<String> values) {
            addCriterion("ware not in", values, "ware");
            return (Criteria) this;
        }

        public Criteria andWareBetween(String value1, String value2) {
            addCriterion("ware between", value1, value2, "ware");
            return (Criteria) this;
        }

        public Criteria andWareNotBetween(String value1, String value2) {
            addCriterion("ware not between", value1, value2, "ware");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNull() {
            addCriterion("costPrice is null");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNotNull() {
            addCriterion("costPrice is not null");
            return (Criteria) this;
        }

        public Criteria andCostpriceEqualTo(Double value) {
            addCriterion("costPrice =", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotEqualTo(Double value) {
            addCriterion("costPrice <>", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThan(Double value) {
            addCriterion("costPrice >", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("costPrice >=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThan(Double value) {
            addCriterion("costPrice <", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThanOrEqualTo(Double value) {
            addCriterion("costPrice <=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceIn(List<Double> values) {
            addCriterion("costPrice in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotIn(List<Double> values) {
            addCriterion("costPrice not in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceBetween(Double value1, Double value2) {
            addCriterion("costPrice between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotBetween(Double value1, Double value2) {
            addCriterion("costPrice not between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceIsNull() {
            addCriterion("preferentialPrice is null");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceIsNotNull() {
            addCriterion("preferentialPrice is not null");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceEqualTo(Double value) {
            addCriterion("preferentialPrice =", value, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceNotEqualTo(Double value) {
            addCriterion("preferentialPrice <>", value, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceGreaterThan(Double value) {
            addCriterion("preferentialPrice >", value, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("preferentialPrice >=", value, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceLessThan(Double value) {
            addCriterion("preferentialPrice <", value, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceLessThanOrEqualTo(Double value) {
            addCriterion("preferentialPrice <=", value, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceIn(List<Double> values) {
            addCriterion("preferentialPrice in", values, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceNotIn(List<Double> values) {
            addCriterion("preferentialPrice not in", values, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceBetween(Double value1, Double value2) {
            addCriterion("preferentialPrice between", value1, value2, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andPreferentialpriceNotBetween(Double value1, Double value2) {
            addCriterion("preferentialPrice not between", value1, value2, "preferentialprice");
            return (Criteria) this;
        }

        public Criteria andSoldIsNull() {
            addCriterion("sold is null");
            return (Criteria) this;
        }

        public Criteria andSoldIsNotNull() {
            addCriterion("sold is not null");
            return (Criteria) this;
        }

        public Criteria andSoldEqualTo(String value) {
            addCriterion("sold =", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldNotEqualTo(String value) {
            addCriterion("sold <>", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldGreaterThan(String value) {
            addCriterion("sold >", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldGreaterThanOrEqualTo(String value) {
            addCriterion("sold >=", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldLessThan(String value) {
            addCriterion("sold <", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldLessThanOrEqualTo(String value) {
            addCriterion("sold <=", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldLike(String value) {
            addCriterion("sold like", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldNotLike(String value) {
            addCriterion("sold not like", value, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldIn(List<String> values) {
            addCriterion("sold in", values, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldNotIn(List<String> values) {
            addCriterion("sold not in", values, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldBetween(String value1, String value2) {
            addCriterion("sold between", value1, value2, "sold");
            return (Criteria) this;
        }

        public Criteria andSoldNotBetween(String value1, String value2) {
            addCriterion("sold not between", value1, value2, "sold");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTurnupIsNull() {
            addCriterion("turnUp is null");
            return (Criteria) this;
        }

        public Criteria andTurnupIsNotNull() {
            addCriterion("turnUp is not null");
            return (Criteria) this;
        }

        public Criteria andTurnupEqualTo(Double value) {
            addCriterion("turnUp =", value, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupNotEqualTo(Double value) {
            addCriterion("turnUp <>", value, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupGreaterThan(Double value) {
            addCriterion("turnUp >", value, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupGreaterThanOrEqualTo(Double value) {
            addCriterion("turnUp >=", value, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupLessThan(Double value) {
            addCriterion("turnUp <", value, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupLessThanOrEqualTo(Double value) {
            addCriterion("turnUp <=", value, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupIn(List<Double> values) {
            addCriterion("turnUp in", values, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupNotIn(List<Double> values) {
            addCriterion("turnUp not in", values, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupBetween(Double value1, Double value2) {
            addCriterion("turnUp between", value1, value2, "turnup");
            return (Criteria) this;
        }

        public Criteria andTurnupNotBetween(Double value1, Double value2) {
            addCriterion("turnUp not between", value1, value2, "turnup");
            return (Criteria) this;
        }

        public Criteria andSuperreturnIsNull() {
            addCriterion("superReturn is null");
            return (Criteria) this;
        }

        public Criteria andSuperreturnIsNotNull() {
            addCriterion("superReturn is not null");
            return (Criteria) this;
        }

        public Criteria andSuperreturnEqualTo(String value) {
            addCriterion("superReturn =", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnNotEqualTo(String value) {
            addCriterion("superReturn <>", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnGreaterThan(String value) {
            addCriterion("superReturn >", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnGreaterThanOrEqualTo(String value) {
            addCriterion("superReturn >=", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnLessThan(String value) {
            addCriterion("superReturn <", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnLessThanOrEqualTo(String value) {
            addCriterion("superReturn <=", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnLike(String value) {
            addCriterion("superReturn like", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnNotLike(String value) {
            addCriterion("superReturn not like", value, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnIn(List<String> values) {
            addCriterion("superReturn in", values, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnNotIn(List<String> values) {
            addCriterion("superReturn not in", values, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnBetween(String value1, String value2) {
            addCriterion("superReturn between", value1, value2, "superreturn");
            return (Criteria) this;
        }

        public Criteria andSuperreturnNotBetween(String value1, String value2) {
            addCriterion("superReturn not between", value1, value2, "superreturn");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andWaretypeIsNull() {
            addCriterion("wareType is null");
            return (Criteria) this;
        }

        public Criteria andWaretypeIsNotNull() {
            addCriterion("wareType is not null");
            return (Criteria) this;
        }

        public Criteria andWaretypeEqualTo(String value) {
            addCriterion("wareType =", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeNotEqualTo(String value) {
            addCriterion("wareType <>", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeGreaterThan(String value) {
            addCriterion("wareType >", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeGreaterThanOrEqualTo(String value) {
            addCriterion("wareType >=", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeLessThan(String value) {
            addCriterion("wareType <", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeLessThanOrEqualTo(String value) {
            addCriterion("wareType <=", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeLike(String value) {
            addCriterion("wareType like", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeNotLike(String value) {
            addCriterion("wareType not like", value, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeIn(List<String> values) {
            addCriterion("wareType in", values, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeNotIn(List<String> values) {
            addCriterion("wareType not in", values, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeBetween(String value1, String value2) {
            addCriterion("wareType between", value1, value2, "waretype");
            return (Criteria) this;
        }

        public Criteria andWaretypeNotBetween(String value1, String value2) {
            addCriterion("wareType not between", value1, value2, "waretype");
            return (Criteria) this;
        }

        public Criteria andWebsiteidIsNull() {
            addCriterion("websiteId is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteidIsNotNull() {
            addCriterion("websiteId is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteidEqualTo(Integer value) {
            addCriterion("websiteId =", value, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidNotEqualTo(Integer value) {
            addCriterion("websiteId <>", value, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidGreaterThan(Integer value) {
            addCriterion("websiteId >", value, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidGreaterThanOrEqualTo(Integer value) {
            addCriterion("websiteId >=", value, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidLessThan(Integer value) {
            addCriterion("websiteId <", value, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidLessThanOrEqualTo(Integer value) {
            addCriterion("websiteId <=", value, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidIn(List<Integer> values) {
            addCriterion("websiteId in", values, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidNotIn(List<Integer> values) {
            addCriterion("websiteId not in", values, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidBetween(Integer value1, Integer value2) {
            addCriterion("websiteId between", value1, value2, "websiteid");
            return (Criteria) this;
        }

        public Criteria andWebsiteidNotBetween(Integer value1, Integer value2) {
            addCriterion("websiteId not between", value1, value2, "websiteid");
            return (Criteria) this;
        }

        public Criteria andModelidIsNull() {
            addCriterion("modelId is null");
            return (Criteria) this;
        }

        public Criteria andModelidIsNotNull() {
            addCriterion("modelId is not null");
            return (Criteria) this;
        }

        public Criteria andModelidEqualTo(Integer value) {
            addCriterion("modelId =", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidNotEqualTo(Integer value) {
            addCriterion("modelId <>", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidGreaterThan(Integer value) {
            addCriterion("modelId >", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidGreaterThanOrEqualTo(Integer value) {
            addCriterion("modelId >=", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidLessThan(Integer value) {
            addCriterion("modelId <", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidLessThanOrEqualTo(Integer value) {
            addCriterion("modelId <=", value, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidIn(List<Integer> values) {
            addCriterion("modelId in", values, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidNotIn(List<Integer> values) {
            addCriterion("modelId not in", values, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidBetween(Integer value1, Integer value2) {
            addCriterion("modelId between", value1, value2, "modelid");
            return (Criteria) this;
        }

        public Criteria andModelidNotBetween(Integer value1, Integer value2) {
            addCriterion("modelId not between", value1, value2, "modelid");
            return (Criteria) this;
        }

        public Criteria andWareurlIsNull() {
            addCriterion("wareURL is null");
            return (Criteria) this;
        }

        public Criteria andWareurlIsNotNull() {
            addCriterion("wareURL is not null");
            return (Criteria) this;
        }

        public Criteria andWareurlEqualTo(String value) {
            addCriterion("wareURL =", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlNotEqualTo(String value) {
            addCriterion("wareURL <>", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlGreaterThan(String value) {
            addCriterion("wareURL >", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlGreaterThanOrEqualTo(String value) {
            addCriterion("wareURL >=", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlLessThan(String value) {
            addCriterion("wareURL <", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlLessThanOrEqualTo(String value) {
            addCriterion("wareURL <=", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlLike(String value) {
            addCriterion("wareURL like", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlNotLike(String value) {
            addCriterion("wareURL not like", value, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlIn(List<String> values) {
            addCriterion("wareURL in", values, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlNotIn(List<String> values) {
            addCriterion("wareURL not in", values, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlBetween(String value1, String value2) {
            addCriterion("wareURL between", value1, value2, "wareurl");
            return (Criteria) this;
        }

        public Criteria andWareurlNotBetween(String value1, String value2) {
            addCriterion("wareURL not between", value1, value2, "wareurl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlIsNull() {
            addCriterion("loveTaobaoURL is null");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlIsNotNull() {
            addCriterion("loveTaobaoURL is not null");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlEqualTo(String value) {
            addCriterion("loveTaobaoURL =", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlNotEqualTo(String value) {
            addCriterion("loveTaobaoURL <>", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlGreaterThan(String value) {
            addCriterion("loveTaobaoURL >", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlGreaterThanOrEqualTo(String value) {
            addCriterion("loveTaobaoURL >=", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlLessThan(String value) {
            addCriterion("loveTaobaoURL <", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlLessThanOrEqualTo(String value) {
            addCriterion("loveTaobaoURL <=", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlLike(String value) {
            addCriterion("loveTaobaoURL like", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlNotLike(String value) {
            addCriterion("loveTaobaoURL not like", value, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlIn(List<String> values) {
            addCriterion("loveTaobaoURL in", values, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlNotIn(List<String> values) {
            addCriterion("loveTaobaoURL not in", values, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlBetween(String value1, String value2) {
            addCriterion("loveTaobaoURL between", value1, value2, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andLovetaobaourlNotBetween(String value1, String value2) {
            addCriterion("loveTaobaoURL not between", value1, value2, "lovetaobaourl");
            return (Criteria) this;
        }

        public Criteria andPictureurlIsNull() {
            addCriterion("pictureURL is null");
            return (Criteria) this;
        }

        public Criteria andPictureurlIsNotNull() {
            addCriterion("pictureURL is not null");
            return (Criteria) this;
        }

        public Criteria andPictureurlEqualTo(String value) {
            addCriterion("pictureURL =", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlNotEqualTo(String value) {
            addCriterion("pictureURL <>", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlGreaterThan(String value) {
            addCriterion("pictureURL >", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlGreaterThanOrEqualTo(String value) {
            addCriterion("pictureURL >=", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlLessThan(String value) {
            addCriterion("pictureURL <", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlLessThanOrEqualTo(String value) {
            addCriterion("pictureURL <=", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlLike(String value) {
            addCriterion("pictureURL like", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlNotLike(String value) {
            addCriterion("pictureURL not like", value, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlIn(List<String> values) {
            addCriterion("pictureURL in", values, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlNotIn(List<String> values) {
            addCriterion("pictureURL not in", values, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlBetween(String value1, String value2) {
            addCriterion("pictureURL between", value1, value2, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andPictureurlNotBetween(String value1, String value2) {
            addCriterion("pictureURL not between", value1, value2, "pictureurl");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("createUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("createUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("createUser =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("createUser <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("createUser >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("createUser >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("createUser <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("createUser <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("createUser like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("createUser not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("createUser in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("createUser not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("createUser between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("createUser not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("updateUser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("updateUser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("updateUser =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("updateUser <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("updateUser >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("updateUser >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("updateUser <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("updateUser <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("updateUser like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("updateUser not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("updateUser in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("updateUser not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("updateUser between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("updateUser not between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterionForJDBCDate("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterionForJDBCTime("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterionForJDBCTime("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterionForJDBCTime("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterionForJDBCTime("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("updateDate is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("updateDate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterionForJDBCDate("updateDate =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("updateDate <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("updateDate >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("updateDate >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterionForJDBCDate("updateDate <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("updateDate <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterionForJDBCDate("updateDate in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("updateDate not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("updateDate between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("updateDate not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterionForJDBCTime("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterionForJDBCTime("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterionForJDBCTime("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterionForJDBCTime("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}