package com.mybatisDemo.entity;

import java.util.Date;

public class Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.ware
     *
     * @mbggenerated
     */
    private String ware;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.costPrice
     *
     * @mbggenerated
     */
    private Double costprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.preferentialPrice
     *
     * @mbggenerated
     */
    private Double preferentialprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.sold
     *
     * @mbggenerated
     */
    private String sold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.turnUp
     *
     * @mbggenerated
     */
    private Double turnup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.superReturn
     *
     * @mbggenerated
     */
    private String superreturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.wareType
     *
     * @mbggenerated
     */
    private String waretype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.websiteId
     *
     * @mbggenerated
     */
    private Integer websiteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.modelId
     *
     * @mbggenerated
     */
    private Integer modelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.wareURL
     *
     * @mbggenerated
     */
    private String wareurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.loveTaobaoURL
     *
     * @mbggenerated
     */
    private String lovetaobaourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.pictureURL
     *
     * @mbggenerated
     */
    private String pictureurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.createUser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.updateUser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.updateDate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.id
     *
     * @return the value of content.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.id
     *
     * @param id the value for content.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.ware
     *
     * @return the value of content.ware
     *
     * @mbggenerated
     */
    public String getWare() {
        return ware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.ware
     *
     * @param ware the value for content.ware
     *
     * @mbggenerated
     */
    public void setWare(String ware) {
        this.ware = ware == null ? null : ware.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.costPrice
     *
     * @return the value of content.costPrice
     *
     * @mbggenerated
     */
    public Double getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.costPrice
     *
     * @param costprice the value for content.costPrice
     *
     * @mbggenerated
     */
    public void setCostprice(Double costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.preferentialPrice
     *
     * @return the value of content.preferentialPrice
     *
     * @mbggenerated
     */
    public Double getPreferentialprice() {
        return preferentialprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.preferentialPrice
     *
     * @param preferentialprice the value for content.preferentialPrice
     *
     * @mbggenerated
     */
    public void setPreferentialprice(Double preferentialprice) {
        this.preferentialprice = preferentialprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.sold
     *
     * @return the value of content.sold
     *
     * @mbggenerated
     */
    public String getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.sold
     *
     * @param sold the value for content.sold
     *
     * @mbggenerated
     */
    public void setSold(String sold) {
        this.sold = sold == null ? null : sold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.type
     *
     * @return the value of content.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.type
     *
     * @param type the value for content.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.turnUp
     *
     * @return the value of content.turnUp
     *
     * @mbggenerated
     */
    public Double getTurnup() {
        return turnup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.turnUp
     *
     * @param turnup the value for content.turnUp
     *
     * @mbggenerated
     */
    public void setTurnup(Double turnup) {
        this.turnup = turnup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.superReturn
     *
     * @return the value of content.superReturn
     *
     * @mbggenerated
     */
    public String getSuperreturn() {
        return superreturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.superReturn
     *
     * @param superreturn the value for content.superReturn
     *
     * @mbggenerated
     */
    public void setSuperreturn(String superreturn) {
        this.superreturn = superreturn == null ? null : superreturn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.description
     *
     * @return the value of content.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.description
     *
     * @param description the value for content.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.wareType
     *
     * @return the value of content.wareType
     *
     * @mbggenerated
     */
    public String getWaretype() {
        return waretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.wareType
     *
     * @param waretype the value for content.wareType
     *
     * @mbggenerated
     */
    public void setWaretype(String waretype) {
        this.waretype = waretype == null ? null : waretype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.websiteId
     *
     * @return the value of content.websiteId
     *
     * @mbggenerated
     */
    public Integer getWebsiteid() {
        return websiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.websiteId
     *
     * @param websiteid the value for content.websiteId
     *
     * @mbggenerated
     */
    public void setWebsiteid(Integer websiteid) {
        this.websiteid = websiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.modelId
     *
     * @return the value of content.modelId
     *
     * @mbggenerated
     */
    public Integer getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.modelId
     *
     * @param modelid the value for content.modelId
     *
     * @mbggenerated
     */
    public void setModelid(Integer modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.wareURL
     *
     * @return the value of content.wareURL
     *
     * @mbggenerated
     */
    public String getWareurl() {
        return wareurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.wareURL
     *
     * @param wareurl the value for content.wareURL
     *
     * @mbggenerated
     */
    public void setWareurl(String wareurl) {
        this.wareurl = wareurl == null ? null : wareurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.loveTaobaoURL
     *
     * @return the value of content.loveTaobaoURL
     *
     * @mbggenerated
     */
    public String getLovetaobaourl() {
        return lovetaobaourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.loveTaobaoURL
     *
     * @param lovetaobaourl the value for content.loveTaobaoURL
     *
     * @mbggenerated
     */
    public void setLovetaobaourl(String lovetaobaourl) {
        this.lovetaobaourl = lovetaobaourl == null ? null : lovetaobaourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.pictureURL
     *
     * @return the value of content.pictureURL
     *
     * @mbggenerated
     */
    public String getPictureurl() {
        return pictureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.pictureURL
     *
     * @param pictureurl the value for content.pictureURL
     *
     * @mbggenerated
     */
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl == null ? null : pictureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.createUser
     *
     * @return the value of content.createUser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.createUser
     *
     * @param createuser the value for content.createUser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.updateUser
     *
     * @return the value of content.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.updateUser
     *
     * @param updateuser the value for content.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.createDate
     *
     * @return the value of content.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.createDate
     *
     * @param createdate the value for content.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.createTime
     *
     * @return the value of content.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.createTime
     *
     * @param createtime the value for content.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.updateDate
     *
     * @return the value of content.updateDate
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.updateDate
     *
     * @param updatedate the value for content.updateDate
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.updateTime
     *
     * @return the value of content.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.updateTime
     *
     * @param updatetime the value for content.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}